In [139]:
import numpy as np
from __future__ import division

In [166]:
am = np.array([[2.,-5.,4.],[1.,3.,-6.],[-1.,-2.,5.]])
am

array([[ 2., -5.,  4.],
       [ 1.,  3., -6.],
       [-1., -2.,  5.]])

In [167]:
bm = np.array([[1.],[-10.],[9.]])
bm

array([[  1.],
       [-10.],
       [  9.]])

In [150]:
def decomposicao(a):
    n=len(a)
    for k in range(0, n - 1):
        for i in range(k+1, n):
                fator = a[i,k]/a[k,k]
                a[i,k] = fator
                a[i,k+1:n] = a[i,k+1:n] - fator*a[k,k+1:n]
    
    return a

In [156]:
decomposicao(am)

array([[ 2.        , -5.        ,  4.        ],
       [ 0.5       ,  5.5       , -8.        ],
       [-0.5       , -0.81818182,  0.45454545]])

In [164]:
def sistema(matriz,b):
    a=decomposicao(matriz)
    n=len(a)
    
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
        b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    
    return b

In [168]:
sistema(am,bm)

array([[37.88],
       [35.56],
       [25.76]])